name: Lambda Runners
on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/lambda-runners.yml
      - "modules/runners/lambdas/runners/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12
    defaults:
      run:
        working-directory: modules/runners/lambdas/runners

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build
