name: Lambda Syncer
env:
  lambda_name: runner-binaries-syncer
  lambda_path: modules/runner-binaries-syncer/lambdas/runner-binaries-syncer
on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/lambda-runner-binaries-syncer.yml
      - "modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12
    defaults:
      run:
        working-directory: ${{ env.lambda_path }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build
